// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require('express');

  app = express.createServer();

  port = process.env.PORT || 3000;

  app.get('/', function(request, response) {
    return response.send('Hello Engine Yard Cloud from CoffeeScript!');
  });

  app.listen(port);

}).call(this);
